### ISSUE TITLE
Update dependency versions

### ISSUE THREAD

**Issue by stevenvachon** [shinnn/output-file#2]

**Comment by shinnn** [comment]
Bot are up to date. https://github.com/shinnn/output-file/blob/d55d2a54d3f316e3882d8b0a4ad7b0dd05c13b6c/package.json#L30-L31

**Comment by stevenvachon** [comment]
https://david-dm.org/shinnn/output-file?type=dev

**Comment by stevenvachon** [comment]
They are?: https://david-dm.org/shinnn/output-file?type=dev

**Comment by shinnn** [comment]
I have no interest in keeping the conversational ball rolling in vain. If you have a specific suggestion or question, write more detailed issue description first.
